In [1]:
import pandas as pd
from pathlib import Path

print("Pandas version:", pd.__version__)
print("Current working directory:", Path.cwd())

Pandas version: 3.0.6
Current working directory: C:\Users\fatim\Documents\network-intrusion-eda\notebooks

In [2]:
from pathlib import Path

current_dir = Path.cwd()

if current_dir.name == "notebooks":
    project_dir = current_dir.parent
else:
    project_dir = current_dir

print("Project directory:", project_dir)

nsl_train_path = project_dir / "data" / "raw" / "nsl_kdd" / "KDDTrain+.txt"
nsl_test_path = project_dir / "data" / "raw" / "nsl_kdd" / "KDDTest+.txt"

print("Training file exists:", nsl_train_path.exists())
print("Testing file exists:", nsl_test_path.exists())

assert nsl_train_path.is_file(), "NSL-KDD training file not found!"
assert nsl_test_path.is_file(), "NSL-KDD testing file not found!"

Project directory: C:\Users\fatim\Documents\network-intrusion-eda
Training file exists: True
Testing file exists: True

In [3]:
nsl_columns = [
    "duration",
    "protocol_type",
    "service",
    "flag",
    "src_bytes",
    "dst_bytes",
    "land",
    "wrong_fragment",
    "urgent",
    "hot",
    "num_failed_logins",
    "logged_in",
    "num_compromised",
    "root_shell",
    "su_attempted",
    "num_root",
    "num_file_creations",
    "num_shells",
    "num_access_files",
    "num_outbound_cmds",
    "is_host_login",
    "is_guest_login",
    "count",
    "srv_count",
    "serror_rate",
    "srv_serror_rate",
    "rerror_rate",
    "srv_rerror_rate",
    "same_srv_rate",
    "diff_srv_rate",
    "srv_diff_host_rate",
    "dst_host_count",
    "dst_host_srv_count",
    "dst_host_same_srv_rate",
    "dst_host_diff_srv_rate",
    "dst_host_same_src_port_rate",
    "dst_host_srv_diff_host_rate",
    "dst_host_serror_rate",
    "dst_host_srv_serror_rate",
    "dst_host_rerror_rate",
    "dst_host_srv_rerror_rate",
    "attack_type",
    "difficulty_level"
]

print("Number of column names:", len(nsl_columns))

assert len(nsl_columns) == 43

Number of column names: 43

In [4]:
nsl_train = pd.read_csv(
    nsl_train_path,
    header=None,
    names=nsl_columns
)

nsl_test = pd.read_csv(
    nsl_test_path,
    header=None,
    names=nsl_columns
)

print("NSL-KDD Training:", nsl_train.shape)
print("NSL-KDD Testing:", nsl_test.shape)

NSL-KDD Training: (125973, 43)
NSL-KDD Testing: (22544, 43)

In [5]:
display(nsl_train.head())

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,attack_type,difficulty_level
0,0,tcp,ftp_data,SF,491,0,0,0,0,0,...,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,normal,20
1,0,udp,other,SF,146,0,0,0,0,0,...,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal,15
2,0,tcp,private,S0,0,0,0,0,0,0,...,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,neptune,19
3,0,tcp,http,SF,232,8153,0,0,0,0,...,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal,21
4,0,tcp,http,SF,199,420,0,0,0,0,...,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal,21

In [6]:
nsl_train[
    ["duration", "protocol_type", "service",
     "src_bytes", "dst_bytes", "attack_type", "difficulty_level"]
].head()

,duration,protocol_type,service,src_bytes,dst_bytes,attack_type,difficulty_level
0,0,tcp,ftp_data,491,0,normal,20
1,0,udp,other,146,0,normal,15
2,0,tcp,private,0,0,neptune,19
3,0,tcp,http,232,8153,normal,21
4,0,tcp,http,199,420,normal,21

In [7]:
print("NSL-KDD Training Data Types:")
print(nsl_train.dtypes.to_string())

NSL-KDD Training Data Types:
duration                         int64
protocol_type                      str
service                            str
flag                               str
src_bytes                        int64
dst_bytes                        int64
land                             int64
wrong_fragment                   int64
urgent                           int64
hot                              int64
num_failed_logins                int64
logged_in                        int64
num_compromised                  int64
root_shell                       int64
su_attempted                     int64
num_root                         int64
num_file_creations               int64
num_shells                       int64
num_access_files                 int64
num_outbound_cmds                int64
is_host_login                    int64
is_guest_login                   int64
count                            int64
srv_count                        int64
serror_rate                    float64
srv_serror_rate                float64
rerror_rate                    float64
srv_rerror_rate                float64
same_srv_rate                  float64
diff_srv_rate                  float64
srv_diff_host_rate             float64
dst_host_count                   int64
dst_host_srv_count               int64
dst_host_same_srv_rate         float64
dst_host_diff_srv_rate         float64
dst_host_same_src_port_rate    float64
dst_host_srv_diff_host_rate    float64
dst_host_serror_rate           float64
dst_host_srv_serror_rate       float64
dst_host_rerror_rate           float64
dst_host_srv_rerror_rate       float64
attack_type                        str
difficulty_level                 int64

In [8]:
numeric_columns = nsl_train.select_dtypes(
    include="number"
).columns.tolist()

categorical_columns = nsl_train.select_dtypes(
    include=["object", "str", "category"]
).columns.tolist()

print("Numerical columns:", len(numeric_columns))
print("Categorical columns:", len(categorical_columns))

print("\nCategorical columns:")
print(categorical_columns)

Numerical columns: 39
Categorical columns: 4

Categorical columns:
['protocol_type', 'service', 'flag', 'attack_type']

In [9]:
print("Number of unique attack labels:")
print(nsl_train["attack_type"].nunique())

print("\nAttack labels:")
print(sorted(nsl_train["attack_type"].unique()))

Number of unique attack labels:
23

Attack labels:
['back', 'buffer_overflow', 'ftp_write', 'guess_passwd', 'imap', 'ipsweep', 'land', 'loadmodule', 'multihop', 'neptune', 'nmap', 'normal', 'perl', 'phf', 'pod', 'portsweep', 'rootkit', 'satan', 'smurf', 'spy', 'teardrop', 'warezclient', 'warezmaster']

In [10]:
nsl_train["traffic_class"] = nsl_train["attack_type"].apply(
    lambda x: "Normal" if x == "normal" else "Attack"
)

print("Training traffic distribution:")
print(nsl_train["traffic_class"].value_counts())

print("\nTraining traffic percentages:")
print(
    nsl_train["traffic_class"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

Training traffic distribution:
traffic_class
Normal    67343
Attack    58630
Name: count, dtype: int64

Training traffic percentages:
traffic_class
Normal    53.46
Attack    46.54
Name: proportion, dtype: float64

In [11]:
train_attacks = set(nsl_train["attack_type"].unique())
test_attacks = set(nsl_test["attack_type"].unique())

print("Unique labels in training:", len(train_attacks))
print("Unique labels in testing:", len(test_attacks))

print("\nLabels found only in testing:")
print(sorted(test_attacks - train_attacks))

print("\nLabels found only in training:")
print(sorted(train_attacks - test_attacks))

Unique labels in training: 23
Unique labels in testing: 38

Labels found only in testing:
['apache2', 'httptunnel', 'mailbomb', 'mscan', 'named', 'processtable', 'ps', 'saint', 'sendmail', 'snmpgetattack', 'snmpguess', 'sqlattack', 'udpstorm', 'worm', 'xlock', 'xsnoop', 'xterm']

Labels found only in training:
['spy', 'warezclient']

In [ ]:
## UNSW-NB15 Dataset Understanding

In [12]:
unsw_train_path = project_dir / "data" / "raw" / "unsw_nb15" / "UNSW_NB15_training-set.csv"
unsw_test_path = project_dir / "data" / "raw" / "unsw_nb15" / "UNSW_NB15_testing-set.csv"

unsw_train = pd.read_csv(unsw_train_path)
unsw_test = pd.read_csv(unsw_test_path)

print("UNSW-NB15 Training:", unsw_train.shape)
print("UNSW-NB15 Testing:", unsw_test.shape)

assert unsw_train.shape == (175341, 45)
assert unsw_test.shape == (82332, 45)

UNSW-NB15 Training: (175341, 45)
UNSW-NB15 Testing: (82332, 45)

In [13]:
print("UNSW-NB15 Column Names:\n")

for i, column in enumerate(unsw_train.columns, start=1):
    print(f"{i:2}. {column}")

UNSW-NB15 Column Names:

 1. id
 2. dur
 3. proto
 4. service
 5. state
 6. spkts
 7. dpkts
 8. sbytes
 9. dbytes
10. rate
11. sttl
12. dttl
13. sload
14. dload
15. sloss
16. dloss
17. sinpkt
18. dinpkt
19. sjit
20. djit
21. swin
22. stcpb
23. dtcpb
24. dwin
25. tcprtt
26. synack
27. ackdat
28. smean
29. dmean
30. trans_depth
31. response_body_len
32. ct_srv_src
33. ct_state_ttl
34. ct_dst_ltm
35. ct_src_dport_ltm
36. ct_dst_sport_ltm
37. ct_dst_src_ltm
38. is_ftp_login
39. ct_ftp_cmd
40. ct_flw_http_mthd
41. ct_src_ltm
42. ct_srv_dst
43. is_sm_ips_ports
44. attack_cat
45. label

In [14]:
print("UNSW-NB15 Data Types:\n")
print(unsw_train.dtypes.to_string())

print("\nNumerical columns:")
print(len(unsw_train.select_dtypes(include="number").columns))

print("\nCategorical columns:")
print(len(unsw_train.select_dtypes(include=["object", "str", "category"]).columns))

UNSW-NB15 Data Types:

id                     int64
dur                  float64
proto                    str
service                  str
state                    str
spkts                  int64
dpkts                  int64
sbytes                 int64
dbytes                 int64
rate                 float64
sttl                   int64
dttl                   int64
sload                float64
dload                float64
sloss                  int64
dloss                  int64
sinpkt               float64
dinpkt               float64
sjit                 float64
djit                 float64
swin                   int64
stcpb                  int64
dtcpb                  int64
dwin                   int64
tcprtt               float64
synack               float64
ackdat               float64
smean                  int64
dmean                  int64
trans_depth            int64
response_body_len      int64
ct_srv_src             int64
ct_state_ttl           int64
ct_dst_ltm             int64
ct_src_dport_ltm       int64
ct_dst_sport_ltm       int64
ct_dst_src_ltm         int64
is_ftp_login           int64
ct_ftp_cmd             int64
ct_flw_http_mthd       int64
ct_src_ltm             int64
ct_srv_dst             int64
is_sm_ips_ports        int64
attack_cat               str
label                  int64

Numerical columns:
41

Categorical columns:
4

In [15]:
print("UNSW-NB15 Training Class Distribution:\n")

print(unsw_train["label"].value_counts().sort_index())

print("\nClass Percentages:\n")

print(
    unsw_train["label"]
    .value_counts(normalize=True)
    .sort_index()
    .mul(100)
    .round(2)
)

UNSW-NB15 Training Class Distribution:

label
0     56000
1    119341
Name: count, dtype: int64

Class Percentages:

label
0    31.94
1    68.06
Name: proportion, dtype: float64

In [16]:
print("UNSW-NB15 Attack Categories:\n")

print(
    unsw_train["attack_cat"]
    .value_counts(dropna=False)
    .to_string()
)

UNSW-NB15 Attack Categories:

attack_cat
Normal            56000
Generic           40000
Exploits          33393
Fuzzers           18184
DoS               12264
Reconnaissance    10491
Analysis           2000
Backdoor           1746
Shellcode          1133
Worms               130

In [17]:
train_categories = set(unsw_train["attack_cat"].dropna().unique())
test_categories = set(unsw_test["attack_cat"].dropna().unique())

print("Training categories:", len(train_categories))
print("Testing categories:", len(test_categories))

print("\nCategories only in testing:")
print(sorted(test_categories - train_categories))

print("\nCategories only in training:")
print(sorted(train_categories - test_categories))

Training categories: 10
Testing categories: 10

Categories only in testing:
[]

Categories only in training:
[]

In [18]:
display(
    unsw_train[
        ["dur", "proto", "service", "sbytes",
         "dbytes", "attack_cat", "label"]
    ].head()
)

        dur proto service  sbytes  dbytes attack_cat  label
0  0.121478   tcp       -     258     172     Normal      0
1  0.649902   tcp       -     734   42014     Normal      0
2  1.623129   tcp       -     364   13186     Normal      0
3  1.681642   tcp     ftp     628     770     Normal      0
4  0.449454   tcp       -     534     268     Normal      0

In [ ]:
## Dataset Summary

In [19]:
dataset_summary = pd.DataFrame([
    {
        "Dataset": "NSL-KDD",
        "Training Rows": len(nsl_train),
        "Testing Rows": len(nsl_test),
        "Total Rows": len(nsl_train) + len(nsl_test),
        "Columns": len(nsl_train.columns) - 1,
        "Categorical Features": 3,
        "Numerical Features": 38,
        "Training Attack %": round(
            (nsl_train["attack_type"] != "normal").mean() * 100, 2
        )
    },
    {
        "Dataset": "UNSW-NB15",
        "Training Rows": len(unsw_train),
        "Testing Rows": len(unsw_test),
        "Total Rows": len(unsw_train) + len(unsw_test),
        "Columns": len(unsw_train.columns),
        "Categorical Features": 3,
        "Numerical Features": 39,
        "Training Attack %": round(
            (unsw_train["label"] == 1).mean() * 100, 2
        )
    }
])

display(dataset_summary)

,Dataset,Training Rows,Testing Rows,Total Rows,Columns,Categorical Features,Numerical Features,Training Attack %
0,NSL-KDD,125973,22544,148517,43,3,38,46.54
1,UNSW-NB15,175341,82332,257673,45,3,39,68.06

In [20]:
output_path = project_dir / "reports" / "dataset_summary.csv"

dataset_summary.to_csv(output_path, index=False)

print("Dataset summary saved to:", output_path)

Dataset summary saved to: C:\Users\fatim\Documents\network-intrusion-eda\reports\dataset_summary.csv

In [21]:
print("File exists:", output_path.exists())

saved_summary = pd.read_csv(output_path)

display(saved_summary)

File exists: True

,Dataset,Training Rows,Testing Rows,Total Rows,Columns,Categorical Features,Numerical Features,Training Attack %
0,NSL-KDD,125973,22544,148517,43,3,38,46.54
1,UNSW-NB15,175341,82332,257673,45,3,39,68.06